title: Market-Based Risk-Neutral Probability Densities for Future Inflation 
description: Download the dataset and view figures that use it
baseurl: "/web-inflationdistributions" 
url: "https://R2RsquaredLSE.github.io"
github_username: R2RsquaredLSE

theme: jekyll-theme-cayman
